const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
const base='https://srpolyvinyl.com/srpolyvinyl/';
const products=[
 ['Artificial Grass','artificial-grass','Artificial-Grass.jpg','artificial-grass.php'],
 ['EVA','eva','EVA.jpg','eva.php'],
 ['PU Resin (Footwear)','pu-resin-footwear','PU-Resin-footware.jpg','pu-resin-footware.php'],
 ['PVC Resin Suspension','pvc-resin-suspension','product1.jpg','pvc-resin-suspension.php'],
 ['PVC Resin Paste','pvc-resin-paste','PVC-Resin-Paste.jpg','pvc-resinp-paste.php'],
 ['PVC Resin Copolymer','pvc-resin-copolymer','PVC-Resin-Copolymer.jpg','pvc-resin-copolymer.php'],
 ['Plasticizers (Primary & Secondary)','plasticizers','product2.jpg','index.php'],
 ['Release Paper','release-paper','product3.jpg','casting-release-paper.php'],
 ['Blowing Agent (Azodicarbonamide)','blowing-agent','product5.jpg','blowing-agent.php'],
 ['PU Adhesive','pu-adhesive','product6.jpg','pu-adhesive.php'],
 ['Processing Aid','processing-aid','product7.jpg','index.php'],
 ['CPE','cpe','CPE.jpg','index.php'],
 ['Methyl Tin Stabilizer','methyl-tin-stabilizer','product9.jpg','methyl-tin-stabilizer.php'],
 ['De-aromatised Solvents','de-aromatised-solvents',null,null],
 ['Additives for PVC Leather','additives-for-pvc-leather',null,null],
 ['Chlorinated Paraffin (CPW)','chlorinated-paraffin-cpw',null,null]
].map(([name,slug,image,source],i)=>({name,slug,image,source,number:String(i+1).padStart(2,'0')}));
const productArt=["grass","eva","footwear","resin-powder","resin-powder","resin-powder","chemical-supply","release-paper","blowing-agent","adhesive","resin-powder","resin-powder","chemical-supply","chemical-supply","additives","chemical-supply"];
products.forEach((p,i)=>{p.image="product-"+productArt[i]+".png"});
const descriptions={
 'pvc-resin-suspension':'A PVC thermoplastic resin supplied in different K-value grades. The company website lists applications across pipes, profiles, sheets, cable and artificial leather. Confirm the grade for your intended application.',
 'pvc-resin-paste':'PVC paste resin for grade-specific plastisol applications. Contact S. R. Polyvinyl to discuss your application, preferred grade and quantity.',
 'pvc-resin-copolymer':'PVC Resin Copolymer is listed in the company’s resin portfolio. Enquire with the team for the suitable grade, supplier and current availability.',
 'eva':'Ethylene Vinyl Acetate (EVA) is included in the company’s materials portfolio. Enquire for grade-specific information and suitability for your application.',
 'pu-resin-footwear':'Polyurethane resin for footwear is included in the company’s product range. Discuss your application with the team to confirm the appropriate grade.',
 'blowing-agent':'Listed as Blowing Agent on the source website and renamed Azodicarbonamide in this revised catalogue. Exact grades and technical data are awaiting confirmation.'
};
const main=document.querySelector('main');
const hero=main.innerHTML;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function productImage(p){return p.image?`<img src="assets/${p.image}" alt="${escapeHtml(p.name)} — AI-generated material illustration" loading="lazy">`:`<div class="placeholder"><b>${p.number}</b><span>Product image to be confirmed</span></div>`}
function card(p){return `<a class="product-card" href="#/products/${p.slug}"><div class="product-image">${productImage(p)}</div><div class="card-body"><span class="card-number">MATERIAL / ${p.number}</span><h3>${escapeHtml(p.name)}</h3><span class="text-link">View product</span></div></a>`}
function cta(){return `<section class="cta"><div class="wrap"><h2>Let’s find the right material<br>for your requirements.</h2><a class="button" href="#/contact">Talk to our team</a></div></section>`}
function head(title,subtitle,parent,visual){return `<section class="page-head${visual ? ` page-head--${visual}` : ''}"><div class="wrap"><div class="crumbs"><a href="#/">Home</a><span>/</span>${parent?'<a href="#/products">Products</a><span>/</span>':''}<span>${escapeHtml(title)}</span></div><p class="eyebrow">S. R. POLYVINYL LIMITED</p><h1>${escapeHtml(title)}</h1>${subtitle?`<p class="lead">${subtitle}</p>`:''}</div></section>`}
function referenceHome(){return "<section class=\"approved-hero\">\n <img class=\"section-photo\" src=\"assets/hero-warehouse.png\" alt=\"Illustrative industrial warehouse with stacked PVC pipes\">\n <div class=\"hero-shade\"></div><div class=\"red-diagonal\" aria-hidden=\"true\"></div>\n <div class=\"wrap hero-content\"><p class=\"eyebrow light\"><span></span>S. R. POLYVINYL LTD.</p><h1>One Stop Solution<br>for <em>PVC Industry</em></h1><p>A distributor and stockist of a wide range of chemical products essential for manufacturing PVC products.</p><div class=\"actions\"><a class=\"button\" href=\"#/products\">Explore Products</a><a class=\"dark-link\" href=\"#/contact\">Contact Us</a></div></div>\n</section>\n<section class=\"approved-about\">\n <div class=\"about-photo\"><img src=\"assets/about-resin.png\" alt=\"Illustrative resin pellets and metal scoop in an industrial setting\" loading=\"lazy\"></div>\n <div class=\"about-copy\"><p class=\"eyebrow\">ABOUT S. R. POLYVINYL.</p><h2>Your Partner in<br>PVC Raw Materials</h2><p>S. R. Polyvinyl Ltd. distributes and stocks a wide range of chemical products for the PVC industry, serving artificial leather, pipe, footwear and other plastics manufacturers.</p>\n <div class=\"strengths\"><div><span>Competitive<br>Pricing</span></div><div><span>Timely<br>Delivery</span></div><div><span>Quality<br>Products</span></div></div>\n <a class=\"text-link\" href=\"#/about\">Discover Our Company</a></div>\n</section>\n<section class=\"approved-products\">\n <img class=\"section-photo\" src=\"assets/materials-studio.png\" alt=\"Illustrative display of polymer pellets and powders in a dark studio\" loading=\"lazy\"><div class=\"product-shade\"></div><div class=\"red-diagonal\" aria-hidden=\"true\"></div>\n <div class=\"product-intro wrap\"><p class=\"eyebrow\">OUR PRODUCTS</p><h2>Materials That Power<br><em>Your Production</em></h2><p>Explore our range of chemical products essential for manufacturing PVC products.</p></div>\n <div class=\"product-actions actions\"><a class=\"button\" href=\"#/products\">View All Products</a><a class=\"dark-link\" href=\"#/contact\">Send an Enquiry</a></div>\n</section>\n"}
function catalogue(){return head('Explore our materials.','A considered portfolio of 16 product groups.',false,'materials')+`<section class="section wrap"><div class="catalogue-top"><span>All products</span><span>16 product groups · Revised catalogue</span></div><div class="cards">${products.map(card).join('')}</div><p class="source-note">Product images are AI-generated illustrations, not photographs of actual stock. Grade, packaging and current availability must be confirmed with the team.</p></section>`+cta()}
function detail(p){if(p.slug==='pvc-resin-paste')return pasteResin(p);const desc=descriptions[p.slug]||(p.source?`${p.name} is listed in the S. R. Polyvinyl company catalogue. Contact the team for technical information and current supply details.`:'Added to the revised 16-group catalogue. Product description, available grades and application information are awaiting company confirmation.');return head(p.name,'',true)+`<section class="section wrap"><div class="detail-grid"><div><div class="detail-image">${productImage(p)}</div><p class="source-note">${p.image?'AI-generated material illustration. Actual product appearance and packaging must be confirmed.':'An approved product image has not yet been supplied.'}</p></div><div><p class="eyebrow">MATERIAL / ${p.number}</p><h2>Product overview</h2><p class="copy">${escapeHtml(desc)}</p><div class="notice">Technical specifications and commercial details are to be confirmed.</div><dl class="specs"><div><dt>Grade / manufacturer</dt><dd>To be confirmed</dd></div><div><dt>Packaging</dt><dd>To be confirmed</dd></div><div><dt>Minimum order</dt><dd>To be confirmed</dd></div><div><dt>Price / availability</dt><dd>On enquiry</dd></div><div><dt>Technical data sheet</dt><dd>To be confirmed</dd></div></dl><div class="actions"><a class="button" href="#/contact?product=${p.slug}">Enquire about this product</a><a class="button outline" href="#/products">All products</a></div><p class="source-note">${p.source?`Source: <a href="${base+p.source}" target="_blank" rel="noopener">Company product listing</a>`:'Catalogue inclusion supplied by the client. Supporting product information is pending.'}</p></div></div></section><section class="story section"><div class="wrap"><div class="section-heading"><h2>Continue exploring.</h2><a class="text-link" href="#/products">Full catalogue</a></div><div class="cards">${products.filter(x=>x!==p).slice(0,4).map(card).join('')}</div></div></section>`}
function about(){return head('PVC Raw Materials Supplier in Delhi','About S. R. Polyvinyl Ltd.')+`<section class="section wrap"><div class="split"><div><p class="eyebrow">OUR STORY</p><h2>Your Partner in<br>PVC Raw Materials.</h2></div><div><p class="copy">Established in 2001, S. R. Polyvinyl Ltd. is a Delhi-based distributor and stockist of chemical raw materials for the PVC and plastics industry. We work with manufacturers in artificial leather, pipes, footwear and related sectors.</p><p class="copy">Our portfolio brings together PVC resins, plasticizers, release paper and specialist additives. Our distribution brands include PAPEX™, Chemplast Sanmar and Payal Polyplast.</p><p class="copy">From selecting a material category to discussing your next order, we begin with your application. Share your required grade, quantity and delivery location so our team can discuss suitable options and confirm availability.</p><a class="text-link" href="#/products">Explore Our Materials</a></div></div><div class="values"><div class="value"><span>01 / EXPERIENCE</span><h3>Serving Industry Since 2001</h3><p>More than two decades in chemical distribution, with a focus on the needs of PVC and plastics manufacturers.</p></div><div class="value"><span>02 / PORTFOLIO</span><h3>Materials for Your Process</h3><p>Browse <a class="text-link" href="#/products/pvc-resin-paste">PVC paste resin</a>, suspension resin, plasticizers and supporting materials in one catalogue.</p></div><div class="value"><span>03 / CONNECTION</span><h3>Talk Directly to Our Team</h3><p>Contact our Delhi office to discuss specifications, pricing, packaging and delivery requirements for your next purchase.</p></div></div></section>`+cta()}
function pasteResin(p){return head('PVC Paste Resin Supplier in Delhi','Paste-grade PVC for artificial leather, coatings and other plastisol applications.',true)+`<section class="section wrap"><div class="detail-grid"><div><div class="detail-image">${productImage(p)}</div><p class="source-note">AI-generated material illustration. Actual appearance and packaging depend on the selected grade.</p></div><div><p class="eyebrow">PVC RESIN PASTE</p><h2>Start With the Right Grade.</h2><p class="copy">S. R. Polyvinyl Ltd. supplies PVC paste resin as part of its industrial raw-material portfolio. Tell us what you manufacture, the grade you currently use and your required quantity to discuss available options.</p><h3>What Is PVC Paste Resin?</h3><p class="copy">PVC paste resin, also called dispersion resin, is used with plasticizers to prepare plastisols. These formulations can be applied by coating, dipping or moulding and then processed with heat. The resin grade and complete formulation determine the processing behaviour and finished properties.</p><div class="actions"><a class="button" href="#/contact?product=pvc-resin-paste">Enquire About PVC Paste Resin</a><a class="text-link" href="#/products">View All Materials</a></div></div></div></section><section class="story section"><div class="wrap"><p class="eyebrow">APPLICATIONS</p><h2>Where Paste-Grade PVC Is Used</h2><p class="copy">Applications vary by grade. Manufacturer guidance lists uses including:</p><div class="values"><div class="value"><h3>Artificial Leather &amp; Coated Fabrics</h3><p>Leathercloth, tarpaulin coatings and related flexible surfaces.</p></div><div class="value"><h3>Flooring &amp; Wallcoverings</h3><p>Flooring layers and wallpaper formulations using suitable dispersion grades.</p></div><div class="value"><h3>Dipping &amp; Moulding</h3><p>Selected grades for dip, slush and rotational moulding, including boots and other moulded articles.</p></div></div></div></section><section class="section wrap"><div class="split"><div><h2>Discuss Your Grade Requirements</h2><p class="copy">Share your application, processing method, preferred manufacturer or grade, and required quantity. Include your target viscosity and other specification requirements where available.</p></div><div><h3>Before You Order</h3><p class="copy">Confirm the manufacturer's technical data sheet, formulation suitability, packaging, price and delivery availability with our team. These details are specific to the selected product and order.</p><p class="copy">Need supporting materials? Explore our <a class="text-link" href="#/products/plasticizers">plasticizers</a> and <a class="text-link" href="#/products/additives-for-pvc-leather">additives for PVC leather</a>.</p><a class="button" href="#/contact?product=pvc-resin-paste">Discuss Your Requirement</a></div></div></section>`}
function contact(slug){const chosen=products.find(p=>p.slug===slug);return head('Let’s talk materials.','Tell us what you need. Start a conversation with our team.',false,'contact')+`<section class="section wrap contact-grid"><div><p class="eyebrow">GET IN TOUCH</p><h2>A direct line<br>to our team.</h2><div class="contact-block"><h3>Visit our office</h3><p>4261/3, Jai Mata Market,<br>Trinagar, Delhi – 110035, India</p></div><div class="contact-block"><h3>Call us</h3><a href="tel:+918586980901">+91 8586 980 901</a><a href="tel:+918586980905">+91 8586 980 905</a></div><div class="contact-block"><h3>Email us</h3><a href="mailto:srpolyvinyl@gmail.com">srpolyvinyl@gmail.com</a></div><p class="source-note">Contact details from the <a href="${base}contact-us.php" target="_blank" rel="noopener">company website</a>.</p></div><form id="enquiry"><h2>Product enquiry</h2><p class="form-note">Preview only: this form prepares an enquiry for review. Nothing is sent or stored.</p><div class="form-row"><label>Your name *<input name="name" autocomplete="name" required maxlength="100"></label><label>Email address *<input name="email" type="email" autocomplete="email" required maxlength="150"></label></div><label>Company<input name="company" autocomplete="organization" maxlength="150"></label><label>Product group<select name="product"><option value="General enquiry">General enquiry</option>${products.map(p=>`<option value="${escapeHtml(p.name)}" ${chosen===p?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></label><label>Your requirements *<textarea name="message" required maxlength="2000" placeholder="Application, grade, quantity or any questions…"></textarea></label><button class="button" type="submit">Preview enquiry</button><div id="form-result" aria-live="polite"></div></form></section>`}
function closeMenu(){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus()}});
document.addEventListener('click',e=>{if(!e.target.closest('header'))closeMenu()});
nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();main.focus();main.scrollIntoView()});
function render(initial=false){
 const raw=location.hash.slice(1)||'/';const [path,query='']=raw.split('?');let content,title,active;
 if(path==='/'){content=home();title='Home';active='home'}
 else if(path==='/products'){content=catalogue();title='Products';active='products'}
 else if(path.startsWith('/products/')){const p=products.find(p=>p.slug===path.slice(10));if(p){content=detail(p);title=p.name;active='products'}}
 else if(path==='/about'){content=about();title='About us';active='about'}
 else if(path==='/contact'){content=contact(new URLSearchParams(query).get('product'));title='Contact';active='contact'}
 if(!content){content=head('Page not found.','Please return to the catalogue to continue browsing.')+'<section class="section wrap"><a class="button" href="#/products">Explore products</a></section>';title='Page not found'}
 main.innerHTML=content;
 const metadata=path==='/about'?['PVC Raw Materials Supplier in Delhi | S. R. Polyvinyl','Established in 2001, S. R. Polyvinyl supplies PVC resins, plasticizers and industrial raw materials. Explore our portfolio and contact our Delhi team.']:path==='/products/pvc-resin-paste'?['PVC Paste Resin Supplier in Delhi | S. R. Polyvinyl','Explore PVC paste resin for artificial leather, coatings and plastisol applications. Discuss grades, quantities and availability with S. R. Polyvinyl.']:null;
 document.title=metadata?metadata[0]:`${title} | S. R. Polyvinyl — Client Preview`;
 document.querySelector('meta[name="description"]').content=metadata?metadata[1]:'Explore the S. R. Polyvinyl materials catalogue. Separate client design preview.';
 closeMenu();
 document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 const form=document.querySelector('#enquiry');if(form)form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const text=`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nCompany: ${data.get('company')||'Not specified'}\nProduct: ${data.get('product')}\n\nRequirements:\n${data.get('message')}`;document.querySelector('#form-result').innerHTML=`<div class="form-result"><h3>Enquiry preview ready</h3><p>Nothing has been sent. Review your details below.</p><pre>${escapeHtml(text)}</pre><a class="text-link" href="mailto:srpolyvinyl@gmail.com?subject=${encodeURIComponent('Product enquiry: '+data.get('product'))}&body=${encodeURIComponent(text)}">Open in your email app</a></div>`;document.querySelector('#form-result').scrollIntoView({block:'nearest'})});
 if(!initial){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true})}
}
function home(){return referenceHome()+`
<section class="section wrap featured-materials"><div class="section-heading"><div><p class="eyebrow">EXPLORE THE RANGE</p><h2>One portfolio.<br>Many possibilities.</h2></div><div class="section-summary"><p>From PVC resins and plasticizers to release paper and specialist additives, find a starting point for your next requirement.</p><a class="text-link" href="#/products">Explore all 16 product groups</a></div></div><div class="cards">${[products[3],products[6],products[7],products[14]].map(card).join('')}</div><p class="source-note">AI-generated material illustrations. Product grades and specifications are confirmed on enquiry.</p></section>
<section class="industries-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">INDUSTRIES WE SERVE</p><h2>Materials behind<br>everyday possibilities.</h2></div><p class="section-summary">Our company portfolio serves manufacturers across artificial leather, pipe, footwear and other plastics industries.</p></div><div class="industry-grid">
<article class="industry-card"><img src="assets/product-release-paper.png" alt="Illustrative release-paper rolls for the artificial leather industry" loading="lazy"><div><span>01 / ARTIFICIAL LEATHER</span><h3>From material to finish.</h3><p>Explore release paper, PVC resins and additives for PVC leather.</p><a class="dark-link" href="#/products/additives-for-pvc-leather">Explore leather additives</a></div></article>
<article class="industry-card"><img src="assets/hero-warehouse.png" alt="Illustrative stacked pipes in an industrial warehouse" loading="lazy"><div><span>02 / PIPES &amp; PROFILES</span><h3>Built around your process.</h3><p>Discuss PVC resin grades and supporting materials for your manufacturing requirements.</p><a class="dark-link" href="#/products/pvc-resin-suspension">Explore PVC resin</a></div></article>
<article class="industry-card"><img src="assets/product-footwear.png" alt="AI-generated illustration of footwear soles and material samples" loading="lazy"><div><span>03 / FOOTWEAR</span><h3>Every step starts here.</h3><p>Discover EVA and PU resin for footwear, and discuss suitable grades with our team.</p><a class="dark-link" href="#/products/pu-resin-footwear">Explore footwear materials</a></div></article>
</div></div></section>
<section class="sourcing-section section"><div class="wrap split"><div><p class="eyebrow">LET'S GET STARTED</p><h2>Your requirements.<br>Our next conversation.</h2><p class="copy">Share your application, preferred grade and quantity. Connect directly with our Delhi office to confirm product information and current availability.</p><a class="button" href="#/contact">Discuss your requirements</a></div><div class="sourcing-steps"><div><span>01</span><div><h3>Tell us the application</h3><p>Let us know what you manufacture and the material you need.</p></div></div><div><span>02</span><div><h3>Confirm the details</h3><p>Discuss grade, manufacturer, packaging and technical documentation.</p></div></div><div><span>03</span><div><h3>Plan the requirement</h3><p>Check quantity, price and delivery availability directly with the team.</p></div></div></div></div></section>`}

window.addEventListener('hashchange',()=>render());render(true);
